add dynamorio tracer hooking libc internal allocation
wapiflapi/villoc pull request #13
Opened 2019-01-18 15:37 UTC by ampotos

A DynamoRIO tool which hook the internal allocator of the libc and print the allocation detail in the right format for villoc.
Tested successfully against /bin/ls;

2019-01-21 11:28 UTC, wapiflapi commented
Looks like this works pretty well ! 

Testing this I stumbled uppon https://github.com/mxmssh/drltrace which seems to work better dans ltrace but have a similar usage. So I think we'd be better of using that instead of rolling our own tracer we'd have to maintain.

2019-01-22 10:01 UTC, wapiflapi commented
drltrace doesn't print return values and also I can't get the config to work properly, so back to your proposal :-)

Some things I'd like to see improved before merging:
  - free shouldn't have a return value, if we can use the same syntax as ltrace it would be perfect:
    `free(0x55616586a670) = <void>`
  - If the target crashes inside a library call it would be nice to have the call logged (obviously without the return value)

2019-01-22 11:37 UTC, ampotos commented
The changes are implemented, the buffering should be thread safe as well (1 buffer per thread).

2019-01-23 16:08 UTC, wapiflapi requested changes
This is starting to look really good/useful :-) I'm looking forward to adding annotation support to this as soon as it is merged.

2019-01-23 16:08 UTC, wapiflapi commented on tracer/dynamorio/README.md
> +Set the environment variable DYNAMORIO_HOME to the absolute path of your DynamoRIO installation\
What's with the `\` ?

2019-01-23 16:08 UTC, wapiflapi commented on tracers/dynamorio/README.md
> +Set the environment variable DYNAMORIO_HOME to the absolute path of your DynamoRIO installation\
What's with the `\` ?
Also can we put in a link to the official releases of dynamorio and specify that people simply need to download, tar -xf and they don't have to "install" anything? (it's scary and sounds complicated otherwise)

2019-01-23 16:08 UTC, wapiflapi commented on tracers/dynamorio/build.sh
> +
We should change to the build script's directory before assuming we're already there.
```bash
SCRIPT_PATH=${0%/*}
if [ "$0" != "$SCRIPT_PATH" ] && [ "$SCRIPT_PATH" != "" ]; then 
    cd $SCRIPT_PATH
fi
```

2019-01-23 16:08 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
> +#define BUF_SIZE (27 + 19 * 2 + 20 * 2)
Please use 1024, I don't want to have to do the math to check this.

2019-01-23 16:08 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
> +}
Why not `memset(buf, 0, BUF_SIZE);` ? Is it not OK to call library functions from within dynamo?

2019-01-23 16:08 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
> +  *user_data = (void *)1;
Please change this to something meaningful like
```C
*bufptr = buf; // We will need to print the buffer in this wrapper.
*bufptr = NULL; // No need to print anything this round, it's an internal call.
```

2019-01-23 16:08 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
> +      *user_data = NULL;
This should be an if/else with the assignment above.

2019-01-23 16:08 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
> +      *user_data = NULL;
It could be something like:

```C
if (buf[0])
    *bufptr = NULL; // No need to print anything this round, it's an internal call.
else
    *bufptr = buf; // We will need to print the buffer in this wrapper.
```

Of course it's the same for all other pre_XX functions.

2019-01-23 16:08 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
> +  *user_data = (void *)1;
This supposes we use `void **bufptr` in our prototype instead of user_data in all functions.

2019-01-23 16:10 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
> +  *user_data = (void *)1;
Then we can use bufptr directly in the poost_hook without having to tls_idx & co, right?

2019-01-23 16:12 UTC, ampotos commented on tracers/dynamorio/villoc_tracer.c
> +}
I build the tool without the libc to be 100% sure it will not interfere with any internal state.

2019-01-23 16:19 UTC, wapiflapi commented
Okay that's good!

On Wed, Jan 23, 2019 at 5:12 PM ampotos <notifications@github.com> wrote:

> *@ampotos* commented on this pull request.
> ------------------------------
>
> In tracers/dynamorio/villoc_tracer.c
> <https://github.com/wapiflapi/villoc/pull/13#discussion_r250262900>:
>
> > +#include "drmgr.h"
> +
> +// reallocarray is the longest possible string to log
> +// so the max size the realloc can have will be the of the per thread logging
> +#define BUF_SIZE (27 + 19 * 2 + 20 * 2)
> +
> +int tls_idx;
> +
> +void reset_buf()
> +{
> +  void *drc = dr_get_current_drcontext();
> +
> +  char *buf = drmgr_get_tls_field(drc, tls_idx);
> +  for (size_t i = 0; i < BUF_SIZE; i++)
> +    buf[i] = 0;
> +}
>
> I build the tool without the libc to be 100% sure it will not interfere
> with any internal state.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/wapiflapi/villoc/pull/13#discussion_r250262900>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABi3R-2mUXWdnRHxZgIADJH6ZU66JMhFks5vGInRgaJpZM4aIIni>
> .
>

2019-01-23 16:19 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
> +}
okay that's good!

2019-01-23 16:40 UTC, wapiflapi requested changes

2019-01-23 16:40 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
>    dr_snprintf(drmgr_get_tls_field(drc, tls_idx), BUF_SIZE, "free(%p", drwrap_get_arg(wrapctx, 0));
You have `buf`, why get it again?

2019-01-23 16:45 UTC, wapiflapi commented on tracers/dynamorio/villoc_tracer.c
>    dr_snprintf(drmgr_get_tls_field(drc, tls_idx), BUF_SIZE, "free(%p", drwrap_get_arg(wrapctx, 0));
in the spirit of not calling `drmgr_get_tls_field` to often we should probably pass buf as an argument to `reset_buf` instead of getting it again from there.

Please check all calls to `drmgr_get_tls_field` and then we're good to merge!

2019-01-23 16:48 UTC, wapiflapi approved these changes

2019-01-23 16:49 UTC, merged